services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    networks:
      - backend

  app:
    image: juser:latest
    ports:
      - "8080:8080"
    environment:
      - DB_FORMAT_SQL=false
      - DB_SHOW_SQL=false
      - DB_INIT_MODE=always
      - JWT_SECRET=V6xBhEri2PHaO6g8nrTLHIZ3bu3kvu8tAjcSRVfHzrDpQsEO44QJSOgjS169sNDf
      - DB_PLATFORM=postgres
      - DB_URL=jdbc:postgresql://db:5432/userdb
      - DB_DRIVER_CLASS_NAME=org.postgresql.Driver
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DIALECT=org.hibernate.dialect.PostgreSQLDialect
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT:11211
      - APP_PROFILE=prod
    depends_on:
      - db
      - memcached
    networks:
      - backend

volumes:
  postgres_data:
  postgres_data_tablespace:

networks:
  backend:
    driver: bridge