app:
  schema: ${APP_SCHEMA:ac} # Default schema for the application

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}

# Database
spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:userdb} # jdbc:h2:mem:userdb for H2 in-memory | jdbc:postgresql://localhost:5432/userdb for PostgreSQL
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:password}
    hikari:
      max-lifetime: ${DB_MAX_LIFETIME:1800000} # 30 minutes
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000} # 30 seconds
      idle-timeout: ${DB_IDLE_TIMEOUT:600000} # 10 minutes
      minimum-idle: ${DB_MINIMUM_IDLE:5} # Minimum number of idle connections
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:10} # Maximum number of connections in the pool
      pool-name: ${DB_POOL_NAME:UserDBPool}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect} # org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: ${DB_GENERATE_DDL:false} # true to generate DDL
    show-sql: ${DB_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:none} # none, validate, update, create, create-drop
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.H2Dialect} # org.hibernate.dialect.PostgreSQLDialect
        format_sql: ${DB_FORMAT_SQL:false}
        show_sql: ${DB_SHOW_SQL:false}
      default_schema: ${DB_SCHEMA:ac}
      hbm2ddl:
        create_namespaces: ${DB_CREATE_NAMESPACES:false}
  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_CLIENT_BASE_URL:http://localhost:9080} # URL to the Spring Boot Admin client
        instance:
          service-url: ${BOOT_ADMIN_INSTANCE_SERVICE_URL:http://localhost:8080/actuator} # URL to the Spring Boot Admin server
  devtools:
    livereload:
      enabled: ${DEVTOOLS_LIVERELOAD_ENABLED:false}

# JWT
jwt:
  secret: ${JWT_SECRET:mysecretkey} # Secret key for signing JWT tokens
  expiration: ${JWT_EXP:3600000} # 1 hour in milliseconds

# Password regex
regexes:
  password: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$"
  email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

userApi:
  openapi:
    dev-url: http://localhost:${SERVER_PORT:8080}
    prod-url: ${PROD_DOMAIN:https://user-api.com}:${PROD_PORT:8080}
    name: "User API"
    email: "test@local.com"